name: Build Windows

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name : Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '24'
                cache: npm

            - name: Clean install frontend dependencies
              run: npm ci 

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
            
            - name: Build
              run: npm run tauri build

            - name: Create ZIP
              shell: pwsh
              run: |
                Compress-Archive -Path src-tauri\target\release\*.exe -DestinationPath serial-viewer-windows-x86_64.zip
            
            - name: Upload ZIP
              uses: actions/upload-artifact@v4
              with:
                name: serial-viewer-windows-x86_64
                path: serial-viewer-windows-x86_64.zip