name: Release Windows

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
    release:
        runs-on: windows-latest

        steps:
            - name : Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
                cache: npm

            - name: Clean install dependencies
              run: npm ci 

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
            
            - name: Build and release app
              uses: tauri-apps/tauri-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tagName: v__VERSION__
                releaseName: "Serial Viewer v__VERSION__"
                releaseBody: "Windows release"
                releaseDraft: true 
                prerelease: false
